name = "PyonPlus"
author = "Oxedyne, Nyxie and Sini"
version = "0.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b708c66bd5ff7642a75d5f824754dfe2810e43b4c6132b6a6eb10073b8e166b6"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
