name = "Pyon Plus"
author = "Oxedyne & Nyxie"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f12b3d0f19f51790ce53916b1a781d883d79b7980d576b3ef6cb16c59e7b8a17"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
